name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install LaTeX
        run: sudo apt install texlive-full
      - name: Install fonts
        run: mkdir -p ~/.fonts && cp fonts/* ~/.fonts && fc-cache -fv
      - name: Compile cv.tex
        run: xelatex -synctex=1 -interaction=nonstopmode -file-line-error cv.tex
      - name: Upload PDF
        uses: actions/upload-artifact@master
        with:
          name: CV (PDF)
          path: cv.pdf
