name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Install fonts
        run: cp fonts/* ~/.font && fc-cache -fv
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: cv.tex
          compiler: xelatex
      - name: Upload PDF
        uses: actions/upload-artifact@master
        with:
          name: CV (PDF)
          path: cv.pdf
